"use client";

import { Suspense, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Megaphone } from "lucide-react";

const CHANNEL_OPTIONS: { value: string; label: string }[] = [
  { value: "google", label: "Google" },
  { value: "meta", label: "Meta" },
  { value: "linkedin", label: "LinkedIn" },
  { value: "youtube", label: "YouTube" },
  { value: "reddit", label: "Reddit" },
];

interface ChannelPlan {
  channel: string;
  budget: number;
  creative_angle: string;
  audience_notes: string;
}

interface PlanDeliverable {
  id: string;
  title: string;
  content: { summary: string; channels: ChannelPlan[]; total_budget: number };
}

const DISCLAIMER =
  "This is a creative and budget recommendation. Blue Diamond Cre8tive does not manage ad accounts or spend on your behalf. Use this plan with your own media buyer or ad platform account.";

function PaidMediaPlanInner() {
  const searchParams = useSearchParams();
  const projectId = searchParams.get("projectId") || "";

  const [totalBudget, setTotalBudget] = useState("");
  const [channels, setChannels] = useState<string[]>([]);
  const [goal, setGoal] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [plan, setPlan] = useState<PlanDeliverable | null>(null);

  function toggleChannel(value: string) {
    setChannels((prev) => (prev.includes(value) ? prev.filter((c) => c !== value) : [...prev, value]));
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const budgetNum = Number(totalBudget);
    if (!budgetNum || budgetNum <= 0 || channels.length === 0 || !goal.trim()) return;
    setSubmitting(true);
    setError(null);
    setPlan(null);
    try {
      const res = await fetch("/api/dashboard/paid-media-plan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ totalBudget: budgetNum, channels, goal, projectId: projectId || undefined }),
      });
      if (!res.ok) {
        const { error: err } = await res.json().catch(() => ({ error: "Failed to generate plan." }));
        setError(err);
        return;
      }
      const { deliverable } = await res.json();
      setPlan(deliverable);
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div>
      <div className="dash-page-head">
        <div>
          <h1>Paid Media Plan</h1>
          <p>Creative direction and a recommended budget split, generated by Henry.</p>
        </div>
      </div>

      <div className="dash-disclaimer">
        <Megaphone size={16} style={{ flexShrink: 0, marginTop: 1 }} />
        <span>{DISCLAIMER}</span>
      </div>

      <form className="kanban-new-task-panel" onSubmit={handleSubmit} style={{ maxWidth: 640 }}>
        <div className="field">
          <label htmlFor="pmp-budget">Total budget</label>
          <input id="pmp-budget" type="number" min="1" value={totalBudget} onChange={(e) => setTotalBudget(e.target.value)} placeholder="e.g. 5000" required />
        </div>
        <div className="field">
          <label>Channels</label>
          <div className="checkbox-grid">
            {CHANNEL_OPTIONS.map((c) => (
              <label key={c.value}>
                <input type="checkbox" checked={channels.includes(c.value)} onChange={() => toggleChannel(c.value)} />
                {c.label}
              </label>
            ))}
          </div>
        </div>
        <div className="field">
          <label htmlFor="pmp-goal">Goal</label>
          <textarea id="pmp-goal" rows={2} value={goal} onChange={(e) => setGoal(e.target.value)} placeholder="e.g. lead generation for a new product line" required />
        </div>
        {error && <div className="form-error">{error}</div>}
        <div style={{ display: "flex", gap: 10, marginTop: 6 }}>
          <button type="submit" className="btn-solid" disabled={submitting}>
            {submitting ? "Generating…" : "Generate plan"}
          </button>
        </div>
      </form>

      {plan && (
        <div className="content-card">
          <h3>{plan.title}</h3>
          {plan.content.summary && <p>{plan.content.summary}</p>}
          {plan.content.channels.map((c) => (
            <div key={c.channel} style={{ marginTop: 14 }}>
              <strong style={{ textTransform: "capitalize" }}>{c.channel}</strong>: ${c.budget.toLocaleString()}
              <p style={{ margin: "4px 0" }}>{c.creative_angle}</p>
              <p style={{ margin: 0, fontSize: 12.5, color: "var(--muted)" }}>{c.audience_notes}</p>
            </div>
          ))}
          <div className="dash-disclaimer" style={{ marginTop: 16, marginBottom: 0 }}>
            <Megaphone size={16} style={{ flexShrink: 0, marginTop: 1 }} />
            <span>{DISCLAIMER}</span>
          </div>
        </div>
      )}
    </div>
  );
}

export default function PaidMediaPlanPage() {
  return (
    <Suspense fallback={null}>
      <PaidMediaPlanInner />
    </Suspense>
  );
}
